//
// GeoVPN nftables Ruleset and Sets Generator
//
'use strict';

import * as fs from 'fs';
import * as util from './util.uc';

function render_ruleset(config, geo_cidrs, active_profile) {
	let main = config.main || {};
	let mode = main.mode || 'bypass';
	let shift = +main.mark_shift || 24;
	let vpn_mark = sprintf('0x%08x', (1 << shift));
	let direct_mark = sprintf('0x%08x', (2 << shift));
	let mark_mask = sprintf('0x%08x', (0xf << shift));
	let clear_mask = sprintf('0x%08x', (~(0xf << shift)) & 0xffffffff);
	let tun_dev = main.tun_dev || 'geovpn0';
	let kill_switch = (main.kill_switch == '1' || main.kill_switch == true);
	let private_direct = (main.private_direct != '0' && main.private_direct != false);
	let block_dot = (main.block_dot != '0' && main.block_dot != false);
	let dns_hijack = (main.dns_hijack != '0' && main.dns_hijack != false);
	let dyn_timeout = main.dyn_timeout || '6h';

	let lan_ifs = main.lan_ifs || ['br-lan'];
	if (type(lan_ifs) != 'array') lan_ifs = [lan_ifs];

	let lines = [];
	push(lines, '# Generated by GeoVPN — do not edit manually');
	push(lines, 'table inet geovpn');
	push(lines, 'delete table inet geovpn');
	push(lines, '');
	push(lines, 'table inet geovpn {');

	// --- Sets Definition ---
	// LAN interfaces
	let if_elements = [];
	for (let i in lan_ifs) {
		if (util.is_ifname(i)) push(if_elements, sprintf('"%s"', i));
	}
	if (length(if_elements) == 0) push(if_elements, '"br-lan"');
	push(lines, sprintf('  set lan_ifs { type ifname; elements = { %s }; }', join(', ', if_elements)));

	// Always direct sets (VPN servers)
	let always4_elems = [];
	let always6_elems = [];
	if (active_profile && active_profile.remotes) {
		for (let r in active_profile.remotes) {
			let host = split(r, ' ')[0];
			if (util.is_ipv4(host)) push(always4_elems, host);
			else if (util.is_ipv6(host)) push(always6_elems, host);
		}
	}
	push(lines, sprintf('  set always4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }',
		join(', ', always4_elems)));
	push(lines, sprintf('  set always6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }',
		join(', ', always6_elems)));

	push(lines, sprintf('  set always4_dyn { type ipv4_addr; flags timeout; timeout %s; size 1024; }', dyn_timeout));
	push(lines, sprintf('  set always6_dyn { type ipv6_addr; flags timeout; timeout %s; size 1024; }', dyn_timeout));

	// RFC1918 and Private Ranges
	push(lines, '  set private4 { type ipv4_addr; flags interval; elements = { 0.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/3 }; }');
	push(lines, '  set private6 { type ipv6_addr; flags interval; elements = { ::1/128, fc00::/7, fe80::/10, ff00::/8 }; }');

	// GeoIP CIDR sets
	let geo4_elems = (geo_cidrs && geo_cidrs.v4) ? geo_cidrs.v4 : [];
	let geo6_elems = (geo_cidrs && geo_cidrs.v6) ? geo_cidrs.v6 : [];
	push(lines, sprintf('  set geo4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', geo4_elems)));
	push(lines, sprintf('  set geo6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', geo6_elems)));

	// GeoSite dynamic sets (populated by dnsmasq nftset)
	push(lines, sprintf('  set geo4_dyn { type ipv4_addr; flags timeout; timeout %s; size 65536; }', dyn_timeout));
	push(lines, sprintf('  set geo6_dyn { type ipv6_addr; flags timeout; timeout %s; size 65536; }', dyn_timeout));

	// Custom rule sets (CIDR and dynamic domain)
	let cust_d4_elems = [];
	let cust_v4_elems = [];
	let cust_d6_elems = [];
	let cust_v6_elems = [];
	if (config.rules) {
		for (let rule in config.rules) {
			if (rule.enabled != '0' && rule.type == 'cidr') {
				let val = rule.value;
				if (util.is_cidr4(val) || util.is_ipv4(val)) {
					if (rule.action == 'direct') push(cust_d4_elems, val);
					else push(cust_v4_elems, val);
				} else if (util.is_cidr6(val) || util.is_ipv6(val)) {
					if (rule.action == 'direct') push(cust_d6_elems, val);
					else push(cust_v6_elems, val);
				}
			}
		}
	}
	push(lines, sprintf('  set cust_d4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cust_d4_elems)));
	push(lines, sprintf('  set cust_v4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cust_v4_elems)));
	push(lines, sprintf('  set cust_d6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cust_d6_elems)));
	push(lines, sprintf('  set cust_v6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cust_v6_elems)));
	push(lines, sprintf('  set cust_d4_dyn { type ipv4_addr; flags timeout; timeout %s; size 8192; }', dyn_timeout));
	push(lines, sprintf('  set cust_v4_dyn { type ipv4_addr; flags timeout; timeout %s; size 8192; }', dyn_timeout));
	push(lines, sprintf('  set cust_d6_dyn { type ipv6_addr; flags timeout; timeout %s; size 8192; }', dyn_timeout));
	push(lines, sprintf('  set cust_v6_dyn { type ipv6_addr; flags timeout; timeout %s; size 8192; }', dyn_timeout));

	// Client policy sets
	let cli_v_mac_elems = [];
	let cli_d_mac_elems = [];
	let cli_v_ip4_elems = [];
	let cli_d_ip4_elems = [];
	let cli_v_ip6_elems = [];
	let cli_d_ip6_elems = [];
	if (config.clients) {
		for (let cli in config.clients) {
			if (cli.enabled != '0') {
				if (cli.match == 'mac' && util.is_mac(cli.value)) {
					if (cli.policy == 'vpn_all') push(cli_v_mac_elems, cli.value);
					else if (cli.policy == 'direct_all') push(cli_d_mac_elems, cli.value);
				} else if (cli.match == 'ip' || cli.match == 'cidr') {
					if (util.is_ipv4(cli.value) || util.is_cidr4(cli.value)) {
						if (cli.policy == 'vpn_all') push(cli_v_ip4_elems, cli.value);
						else if (cli.policy == 'direct_all') push(cli_d_ip4_elems, cli.value);
					} else if (util.is_ipv6(cli.value) || util.is_cidr6(cli.value)) {
						if (cli.policy == 'vpn_all') push(cli_v_ip6_elems, cli.value);
						else if (cli.policy == 'direct_all') push(cli_d_ip6_elems, cli.value);
					}
				}
			}
		}
	}
	push(lines, sprintf('  set cli_v_mac { type ether_addr; elements = { %s }; }', join(', ', cli_v_mac_elems)));
	push(lines, sprintf('  set cli_d_mac { type ether_addr; elements = { %s }; }', join(', ', cli_d_mac_elems)));
	push(lines, sprintf('  set cli_v_ip4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cli_v_ip4_elems)));
	push(lines, sprintf('  set cli_d_ip4 { type ipv4_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cli_d_ip4_elems)));
	push(lines, sprintf('  set cli_v_ip6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cli_v_ip6_elems)));
	push(lines, sprintf('  set cli_d_ip6 { type ipv6_addr; flags interval; auto-merge; elements = { %s }; }', join(', ', cli_d_ip6_elems)));

	// Upstream DNS sets for marked router queries
	let dns_vpn4_elems = [];
	let dns_vpn6_elems = [];
	let vpn_dns_list = main.dns_vpn_servers || ['1.1.1.1', '9.9.9.9'];
	if (type(vpn_dns_list) != 'array') vpn_dns_list = [vpn_dns_list];
	for (let s in vpn_dns_list) {
		if (util.is_ipv4(s)) push(dns_vpn4_elems, s);
		else if (util.is_ipv6(s)) push(dns_vpn6_elems, s);
	}
	push(lines, sprintf('  set dns_vpn4 { type ipv4_addr; flags interval; elements = { %s }; }', join(', ', dns_vpn4_elems)));
	push(lines, sprintf('  set dns_vpn6 { type ipv6_addr; flags interval; elements = { %s }; }', join(', ', dns_vpn6_elems)));
	push(lines, '  set fetch_vpn4 { type ipv4_addr; flags timeout; timeout 10m; }');
	push(lines, '  set fetch_vpn6 { type ipv6_addr; flags timeout; timeout 10m; }');
	push(lines, '');

	// --- Verdict Helper Chains ---
	push(lines, sprintf('  chain set_direct { ct mark set ct mark & %s | %s accept }', clear_mask, direct_mark));
	push(lines, sprintf('  chain set_vpn    { ct mark set ct mark & %s | %s meta mark set meta mark & %s | %s accept }',
		clear_mask, vpn_mark, clear_mask, vpn_mark));
	push(lines, '');

	// --- Classifier Chain ---
	push(lines, '  chain classify {');
	push(lines, '    ct direction reply accept');
	push(lines, sprintf('    ct mark & %s == %s meta mark set meta mark & %s | %s accept', mark_mask, vpn_mark, clear_mask, vpn_mark));
	push(lines, sprintf('    ct mark & %s == %s accept', mark_mask, direct_mark));
	push(lines, '    ip  daddr @always4     jump set_direct');
	push(lines, '    ip6 daddr @always6     jump set_direct');
	push(lines, '    ip  daddr @always4_dyn jump set_direct');
	push(lines, '    ip6 daddr @always6_dyn jump set_direct');
	push(lines, '    ether saddr @cli_v_mac jump set_vpn');
	push(lines, '    ether saddr @cli_d_mac jump set_direct');
	push(lines, '    ip  saddr @cli_v_ip4   jump set_vpn');
	push(lines, '    ip  saddr @cli_d_ip4   jump set_direct');
	push(lines, '    ip6 saddr @cli_v_ip6   jump set_vpn');
	push(lines, '    ip6 saddr @cli_d_ip6   jump set_direct');
	push(lines, '    ip  daddr @cust_v4_dyn jump set_vpn');
	push(lines, '    ip  daddr @cust_d4_dyn jump set_direct');
	push(lines, '    ip6 daddr @cust_v6_dyn jump set_vpn');
	push(lines, '    ip6 daddr @cust_d6_dyn jump set_direct');
	push(lines, '    ip  daddr @cust_v4     jump set_vpn');
	push(lines, '    ip  daddr @cust_d4     jump set_direct');
	push(lines, '    ip6 daddr @cust_v6     jump set_vpn');
	push(lines, '    ip6 daddr @cust_d6     jump set_direct');

	if (private_direct) {
		push(lines, '    ip  daddr @private4    jump set_direct');
		push(lines, '    ip6 daddr @private6    jump set_direct');
	}

	let geo_action = (mode == 'bypass') ? 'set_direct' : 'set_vpn';
	let default_action = (mode == 'bypass') ? 'set_vpn' : 'set_direct';

	push(lines, sprintf('    ip  daddr @geo4_dyn    jump %s', geo_action));
	push(lines, sprintf('    ip6 daddr @geo6_dyn    jump %s', geo_action));
	push(lines, sprintf('    ip  daddr @geo4        jump %s', geo_action));
	push(lines, sprintf('    ip6 daddr @geo6        jump %s', geo_action));
	push(lines, sprintf('    jump %s', default_action));
	push(lines, '  }');
	push(lines, '');

	// --- Prerouting Hook Chain ---
	push(lines, '  chain pre {');
	push(lines, '    type filter hook prerouting priority mangle; policy accept;');
	push(lines, '    iifname != @lan_ifs return');
	push(lines, '    fib daddr type local return');
	push(lines, '    jump classify');
	push(lines, '  }');
	push(lines, '');

	// --- Router-Originated Traffic Output Chain ---
	push(lines, '  chain out {');
	push(lines, '    type route hook output priority mangle; policy accept;');
	push(lines, sprintf('    ip  daddr @dns_vpn4   meta l4proto { tcp, udp } th dport { 53, 853 } meta mark set meta mark & %s | %s',
		clear_mask, vpn_mark));
	push(lines, sprintf('    ip6 daddr @dns_vpn6   meta l4proto { tcp, udp } th dport { 53, 853 } meta mark set meta mark & %s | %s',
		clear_mask, vpn_mark));
	push(lines, sprintf('    ip  daddr @fetch_vpn4 meta mark set meta mark & %s | %s', clear_mask, vpn_mark));
	push(lines, sprintf('    ip6 daddr @fetch_vpn6 meta mark set meta mark & %s | %s', clear_mask, vpn_mark));
	push(lines, '  }');
	push(lines, '');

	// --- Guard Forward Hook Chain (Kill Switch / IPv6 Block) ---
	push(lines, '  chain guard {');
	push(lines, '    type filter hook forward priority filter - 1; policy accept;');
	if (kill_switch) {
		push(lines, sprintf('    meta mark & %s == %s oifname != "%s" reject with icmpx type admin-prohibited',
			mark_mask, vpn_mark, tun_dev));
	}
	if (main.ipv6 == 'block') {
		push(lines, sprintf('    meta nfproto ipv6 meta mark & %s == %s reject with icmpx type admin-prohibited',
			mark_mask, vpn_mark));
	}
	if (block_dot) {
		push(lines, '    iifname @lan_ifs meta l4proto tcp th dport 853 reject with tcp reset');
		push(lines, '    iifname @lan_ifs meta l4proto udp th dport 853 drop');
	}
	push(lines, '  }');
	push(lines, '');

	// --- DNS Hijack NAT Chain ---
	if (dns_hijack) {
		push(lines, '  chain dns_redirect {');
		push(lines, '    type nat hook prerouting priority dstnat - 1; policy accept;');
		push(lines, '    iifname @lan_ifs fib daddr type != local meta l4proto { tcp, udp } th dport 53 redirect to :53');
		push(lines, '  }');
	}

	push(lines, '}');
	push(lines, '');

	return join('\n', lines);
}

function apply_ruleset(config, geo_cidrs, active_profile) {
	let rules_text = render_ruleset(config, geo_cidrs, active_profile);
	let render_dir = '/var/run/geovpn/render';
	if (!fs.stat(render_dir)) {
		fs.mkdir(render_dir, 0o700);
	}
	let rules_file = render_dir + '/rules.nft';
	let f = fs.open(rules_file, 'w', 0o600);
	if (!f) return false;
	f.write(rules_text);
	f.close();

	// Dry run verification if nft binary exists
	let dry_res = util.safe_exec(['nft', '-c', '-f', rules_file]);
	if (dry_res.code != 0) {
		util.log('error', sprintf('nftables dry-run check failed: %s', dry_res.stderr));
		return false;
	}

	// Apply atomic ruleset
	let apply_res = util.safe_exec(['nft', '-f', rules_file]);
	if (apply_res.code != 0) {
		util.log('error', sprintf('Failed to apply nftables ruleset: %s', apply_res.stderr));
		return false;
	}

	util.log('info', 'nftables ruleset applied successfully');
	return true;
}

function teardown_ruleset() {
	util.safe_exec(['nft', 'delete', 'table', 'inet', 'geovpn']);
	util.log('info', 'nftables table inet geovpn removed');
	return true;
}

export {
	render_ruleset,
	apply_ruleset,
	teardown_ruleset
};
